"""Persistence, provenance, and report generation for Part II."""
from __future__ import annotations

import importlib.metadata
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable

import joblib
import pyarrow as pa
import pyarrow.parquet as pq

from quantum_lake_student.ml import GOOGLE_META_PREDICTION_COLUMNS


PROJECT = Path(__file__).resolve().parents[3]
RESULTS_DIR = PROJECT / "results" / "part2"
MODELS_DIR = RESULTS_DIR / "models"

def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_predictions(path: Path, records: Iterable[dict[str, Any]]) -> None:
    schema = pa.schema(
        [
            ("example_id", pa.string()),
            ("model_id", pa.string()),
            ("label", pa.bool_()),
            ("prediction", pa.bool_()),
            ("probability", pa.float64()),
            ("split", pa.string()),
        ]
    )
    table = pa.Table.from_pylist(list(records), schema=schema)
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(table, path, compression="zstd")


def _sanitize_filename(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value)


def _save_models(artifacts: dict[str, dict[str, Any]]) -> dict[str, str]:
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    locations = {}
    for model_id, artifact in artifacts.items():
        path = MODELS_DIR / f"{_sanitize_filename(model_id)}.joblib"
        joblib.dump(artifact, path)
        locations[model_id] = str(path.relative_to(PROJECT))
    return locations


def _package_versions() -> dict[str, str | None]:
    names = ["numpy", "pyarrow", "scikit-learn", "joblib"]
    versions: dict[str, str | None] = {"python": sys.version.split()[0]}
    for name in names:
        try:
            versions[name] = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            versions[name] = None
    return versions


def _pct(value: float) -> str:
    return f"{100 * value:.1f} %"


def _decoder_label(model_id: str, value: dict[str, Any]) -> str:
    column = value.get("source_column")
    return f"{model_id} ({column.removesuffix('_prediction')})" if column else model_id


def _report_markdown(
    metrics: dict[str, Any],
    diagnostics: dict[str, Any],
    input_counts: dict[str, int],
) -> str:
    """Part II report, generated from this run's numbers.

    Spec: report.md explains "the inputs and targets, why each simple model
    fits its table, results, discarded information, and limitations".
    """
    prior_a, logistic_a = metrics["task_a_prior"], metrics["task_a_logistic"]
    share = diagnostics["task_a"]["positive_weight_share"]
    mlp = metrics["task_c_raw_mlp"]
    task_c = diagnostics["task_c"]

    lines = [
        "# Part II — AI/ML results",
        "",
        "Generated by `make train` from the two Part I ML tables only. Model",
        "performance is not the grading target; this report states the results,",
        "including weak ones, and what they mean.",
        "",
        "## Inputs and targets",
        "",
        f"- `ml_syndrome_decoder_example` ({input_counts['syndrome']:,} rows): 16 ordered",
        "  syndrome bits (4 rounds x 4 checks) predict `logical_error_label`. Each row",
        "  stands for `sample_weight` simulated shots (70 million in total).",
        f"- `ml_google_decoder_example` ({input_counts['google']:,} rows): one hardware shot",
        "  per row; detector-event count, packed detector bits and four supplied",
        "  decoder predictions predict `actual_observable_flip`.",
        "- Splits are used exactly as supplied: models are fitted on `train`,",
        "  thresholds are chosen on `validation`, and every number below is",
        "  measured once on `test`. All models of a task share the same test rows.",
        "",
        "## Why each simple model fits its table",
        "",
        "- **Task A.** The table is aggregated and weighted, so the weighted label",
        "  rate is the natural baseline, and logistic regression accepts",
        "  `sample_weight` directly — the 70 million observations never need to be",
        "  expanded. Sixteen binary inputs suit a linear model.",
        "- **Task B.** The supplied decoders already produce predictions; a",
        "  logistic regression on event density plus their four votes is the",
        "  simplest learnable way to combine them. Distances 3 and 5 are fitted",
        "  separately because they are different codes.",
        "- **Task C.** A small MLP is the simplest model that can, in principle,",
        "  learn non-linear patterns directly from the 200 raw detector bits.",
        "",
        "## Task A — weighted syndrome decoder",
        "",
        _metric_table(metrics, prefix="task_a_"),
        "",
        "**Imbalance.** Logical errors are rare: they carry "
        f"{_pct(share['train'])} of the physical weight in train, {_pct(share['validation'])} in "
        f"validation and {_pct(share['test'])} in the test file (fault rate 0.005). The weighted "
        f"prior ({prior_a['positive_prior']:.4f}) is below 0.5, so the baseline always predicts "
        "*no error*; its logical-error rate is simply the test share of errors "
        f"({prior_a['logical_error_rate']:.3f}) and its balanced accuracy is 0.5.",
        "",
    ]
    if logistic_a["logical_error_rate"] > prior_a["logical_error_rate"]:
        lines.append(
            "**Result.** The logistic model's threshold "
            f"({logistic_a['threshold']:.3f}) was chosen on validation to maximise weighted balanced "
            "accuracy. It therefore flags many shots as errors: it finds most real errors "
            f"(balanced accuracy {logistic_a['balanced_accuracy']:.3f}) but makes more mistakes "
            f"overall, so its logical-error rate ({logistic_a['logical_error_rate']:.3f}) is *higher* "
            f"than the prior's ({prior_a['logical_error_rate']:.3f}). Its probabilities are "
            f"{'better' if logistic_a['brier_score'] < prior_a['brier_score'] else 'not better'} "
            f"calibrated than the prior (Brier {logistic_a['brier_score']:.3f} vs "
            f"{prior_a['brier_score']:.3f}). Which model is \"better\" depends on whether "
            "missing an error or raising a false alarm costs more."
        )
    else:
        lines.append(
            "**Result.** The logistic model "
            f"(threshold {logistic_a['threshold']:.3f}, chosen on validation) reaches a logical-error "
            f"rate of {logistic_a['logical_error_rate']:.3f} against the prior's "
            f"{prior_a['logical_error_rate']:.3f}, with balanced accuracy "
            f"{logistic_a['balanced_accuracy']:.3f}."
        )
    lines += ["", "## Task B — supplied and combined Google decoders", ""]

    for distance in (3, 5):
        prefix = f"task_b_d{distance}_"
        decoders = {k: v for k, v in metrics.items() if k.startswith(f"{prefix}decoder_")}
        best_id = min(decoders, key=lambda k: decoders[k]["logical_error_rate"])
        best = decoders[best_id]
        combined = metrics[f"{prefix}combined"]
        overlap = diagnostics[f"task_b_d{distance}"]["decoder_error_overlap"]
        jaccards = [value["jaccard_error_overlap"] for value in overlap.values()]
        difference = combined["logical_error_rate"] - best["logical_error_rate"]
        lines += [
            f"### Distance {distance}",
            "",
            _metric_table(metrics, prefix=prefix),
            "",
            "| Decoder pair (test errors) | Shared errors | Jaccard overlap |",
            "|---|---:|---:|",
            *[f"| {pair.replace('_prediction', '').replace('__', ' / ')} | {value['shared_errors']:,} | "
              f"{value['jaccard_error_overlap']:.3f} |" for pair, value in overlap.items()],
            "",
            f"The prior is close to 0.5 (logical-error rate {metrics[f'{prefix}prior']['logical_error_rate']:.3f}): "
            "over 25 rounds the observable flips in about half of the shots. The best supplied "
            f"decoder is {_decoder_label(best_id, best)} with {best['logical_error_rate']:.3f}. "
            f"Pairs of decoders share between {min(jaccards):.2f} and {max(jaccards):.2f} of their "
            "errors (Jaccard), so they make **partly different mistakes**, but every decoder is "
            "wrong on many of the same shots. Those shared errors cannot be fixed by combining the "
            f"votes, which is why the linear combined decoder ({combined['logical_error_rate']:.3f}) is "
            + ("only " if difference <= 0 else "")
            + f"{abs(difference):.3f} {'below' if difference < 0 else 'above'} the best single decoder. "
            "Its threshold was chosen on validation only.",
            "",
        ]

    lines += [
        "## Task C — bounded raw-detector prototype",
        "",
        "Only `distance = 3 AND shot_index < 12_500` is used: "
        f"{task_c['subset_rows']:,} shots ({task_c['subset_rows_by_split']['train']:,} train, "
        f"{task_c['subset_rows_by_split']['validation']:,} validation, "
        f"{task_c['subset_rows_by_split']['test']:,} test), 200 detector bits each, unpacked with the "
        "supplied little-endian helper.",
        "",
        _metric_table(metrics, prefix="task_c_"),
        "",
        f"**Result.** The MLP {'converged' if task_c['mlp_converged'] else 'did not converge'} after "
        f"{task_c['mlp_iterations']} iterations (early stopping on 10 % of the training rows). Its "
        f"balanced accuracy is {task_c['train_balanced_accuracy']:.3f} on the training shots but "
        f"{mlp['balanced_accuracy']:.3f} on test — "
        + ("chance level: " if abs(mlp["balanced_accuracy"] - 0.5) < 0.02 else "")
        + "it has not learned a pattern that generalises from "
        f"{task_c['subset_rows_by_split']['train']:,} shots. Without early stopping it fits the "
        "training shots more closely but stays at chance on test.",
        "",
        "**What a flat 200-bit vector does not show.** The 200 inputs are 8 detectors x 25",
        "rounds, but the vector does not say which bit belongs to which detector or round,",
        "which detectors are neighbours on the chip, or that a fired detector usually",
        "pairs with another one nearby in space or time. A decoder relies on exactly",
        "these relations; a fully connected MLP has to rediscover them from the data,",
        "which this small, bounded subset does not allow.",
        "",
        "## Discarded information",
        "",
        "- Task A uses only the 16 syndrome bits: the fault rate is a split key, not a",
        "  feature, and the 4 x 4 round/check structure is flattened.",
        "- Task B's combined model sees one number from the raw data — the share of",
        "  fired detectors — so which detectors fired, the processor location and the",
        "  measurement and sweep bits are not used.",
        "- Task C keeps the raw bits but only for distance 3 and the first 12,500 shots",
        "  of each experiment, and loses the spatial and temporal layout described above.",
        "",
        "## Limitations",
        "",
        "- One fixed split per table; no repeated runs or confidence intervals, so small",
        "  differences (for example between the combined and the best decoder) may not be",
        "  meaningful.",
        "- Thresholds maximise balanced accuracy; a different choice would trade logical-error",
        "  rate against missed errors differently (see Task A).",
        "- Linear models and a single small MLP; no tuning beyond the validation threshold.",
        "- Training and prediction times depend on the machine and are indicative only.",
        "",
    ]
    return "\n".join(lines)


def _metric_table(metrics: dict[str, Any], prefix: str) -> str:
    selected = [(model_id, value) for model_id, value in metrics.items() if model_id.startswith(prefix)]
    if not selected:
        return "No metrics recorded."
    lines = [
        "| Model | Logical-error rate | Balanced accuracy | Brier score | Training s | Prediction s |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for model_id, value in selected:
        def fmt(number: Any) -> str:
            return "n/a" if number is None else f"{float(number):.6f}"
        lines.append(
            f"| {_decoder_label(model_id, value)} | {fmt(value.get('logical_error_rate'))} | "
            f"{fmt(value.get('balanced_accuracy'))} | {fmt(value.get('brier_score'))} | "
            f"{fmt(value.get('training_time_seconds'))} | {fmt(value.get('prediction_time_seconds'))} |"
        )
    return "\n".join(lines)
